# Generated by Django 3.2.25 on 2024-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('time', models.TimeField()),
                ('aging', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('device_type', models.CharField(max_length=20)),
                ('customer_login_type', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_priority', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
    ]
